# OpenAI secrets
OPENAI_API_KEY = "sk-proj-hMeo7dF8NLPB2VU3qyKsT3BlbkFJhvGy5ORey9QI6tXKF4hW"

# Astra DB secrets
ASTRA_ENDPOINT = "https://bbb64f23-8de8-454c-ad2f-2ab0fd1c6b37-us-east-2.apps.astra.datastax.com"
ASTRA_TOKEN = "AstraCS:lPzKpsmbqOfOuwOqQGHhxBLD:0a875be1e3b26ff71b3b2b58853c39b0394fb94b5d363c3cfd5ea278e32408da"

# Optionally: LangSmith secrets for tracing
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_ENDPOINT = ""
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""

[passwords]
# Follow the rule: username = "password"
# Where username defines the Astra Vector Table and the rails.csv experience
postnl = ""
datastax = "test123*"

[languages]
# Follow the rule: username = "localization_code"
# Where localization_code defines the language from localization.csv
postnl = "nl_NL"
datastax = "en_US"

[delete_option]
# Follow the rule: username = "delete_option"
# Where delete_option = True allows the 'Delete Context' button to be shown for that username
datastax = "True"
